baseURL = "https://jonasgerdes.com/"

defaultContentLanguage = 'en'
[languages]
  [languages.de]
    title = "Website von Jonas Gerdes"
    weight = 1

  [languages.en]
    title = "Website of Jonas Gerdes"
    weight = 2

[deployment]
[[deployment.targets]]
name = "production"
URL = "s3://website?endpoint=s3.jonasgerdes.com&region=eu-central-1&s3ForcePathStyle=true"