baseURL = "https://jonasgerdes.dev/"
languageCode = "de-de"
title = "Jonas Gerdes"

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://website?endpoint=s3.jonasgerdes.dev&region=eu-central-1&s3ForcePathStyle=true"