name: build and deploy to prd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.88.1/hugo_0.88.1_Linux-64bit.deb
          sudo apt install ./hugo.deb

      - name: Build website
        run: cd $GITHUB_WORKSPACE && hugo

      - name: Deploy
        run: AWS_ACCESS_KEY_ID="${{ secrets.S3_DEPLOY_USER }}" AWS_SECRET_ACCESS_KEY="${{ secrets.S3_DEPLOY_PASS }}" hugo deploy
